# Node Image for docker on which code will execute
image: node:14
# This is the stages / task to perfom in jobs
stages:
  - build
  - deploy

# caching for reuse
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - dist/

# This command is run before the execution of stages
before_script:
  - npm install

# Job One for making build
build_master:
  stage: build
  script:
  - npm run build
  only: ['main']

# Job Two for deploy build to server
deploy_master:
  stage: deploy
  before_script:
    - "command -v ssh-agent >/dev/null || ( apk add --update openssh )"
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - mkdir .dist
    - cp -r dist/* .dist
    - mv .dist dist
    - zip -r dist.zip dist
    - ssh -o StrictHostKeyChecking=no ubuntu@54.173.243.87 "cd /var/www/html; rm -R dist; rm -R dist.zip"
    - scp -o StrictHostKeyChecking=no dist.zip ubuntu@54.173.243.87:/var/www/html
    - ssh -o StrictHostKeyChecking=no ubuntu@54.173.243.87 "cd /var/www/html; unzip dist.zip"
    - ssh -o StrictHostKeyChecking=no ubuntu@54.173.243.87 "cd /var/www/html; cp .htaccess public/.htaccess"
  only: ['main']
